[package]
name = "day08"
version = "0.1.0"
authors = ["Csatacsirke <battlechicken74@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_aoc = { path = "../lib_aoc" }
regex = "1"